import { Toaster } from "react-hot-toast";
import "./globals.css";
import "@fontsource-variable/mona-sans";

export const metadata = {
  title: "3D-Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={``}
      >
        <Toaster position="top-right"/>
        {children}
      </body>
    </html>
  );
}
